## numpy 모듈의 호출

In [1]:
import numpy as np

## array의 생성

In [4]:
test_array = np.array(["1", "4", 5, 8], float)
test_array

array([1., 4., 5., 8.])

In [5]:
type(test_array[3])

numpy.float64

In [6]:
test_array.dtype

dtype('float64')

In [7]:
test_array.shape

(4,)

In [9]:
matrix = [[1,2,5,8],[1,2,5,8],[1,2,5,8]]
matrix = np.array(matrix, int)

In [12]:
tensor = [[[1,2,5,8],[1,2,5,8],[1,2,5,8]],[[1,2,5,8],[1,2,5,8],[1,2,5,8]],[[1,2,5,8],[1,2,5,8],[1,2,5,8]]]
tensor = np.array(tensor, int)

In [16]:
matrix.shape

(3, 4)

In [17]:
tensor.shape

(3, 3, 4)

In [19]:
matrix.ndim

2

In [20]:
tensor.ndim

3

In [21]:
matrix.size

12

In [22]:
tensor.size

36

## reshape

In [23]:
test_matrix = [[1,2,3,4], [1,2,5,8]]
np.array(test_matrix).shape

(2, 4)

In [24]:
np.array(test_matrix).reshape(8,)

array([1, 2, 3, 4, 1, 2, 5, 8])

In [25]:
np.array(test_matrix).reshape(8,).shape

(8,)

In [27]:
np.array(test_matrix).reshape(2,4).shape

(2, 4)

In [28]:
np.array(test_matrix).reshape(-1,2).shape

(4, 2)

In [29]:
np.array(test_matrix).reshape(2,2,2)

array([[[1, 2],
        [3, 4]],

       [[1, 2],
        [5, 8]]])

In [30]:
np.array(test_matrix).reshape(2,2,2).shape

(2, 2, 2)

## flatten

In [31]:
test_matrix = [[[1,2,3,4],[1,2,5,7]], [[1,2,3,4],[1,2,5,8]]]
np.array(test_matrix).flatten()

array([1, 2, 3, 4, 1, 2, 5, 7, 1, 2, 3, 4, 1, 2, 5, 8])