In [1]:
import numpy as np

In [4]:
test_array = np.arange(1,13).reshape(3,4)
test_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

## sum

In [6]:
test_array.sum(axis=0)

array([15, 18, 21, 24])

In [7]:
test_array.sum(axis=1)

array([10, 26, 42])

## mean, std

In [10]:
test_array.mean(), test_array.mean(axis=0)

(6.5, array([5., 6., 7., 8.]))

In [11]:
test_array.std(), test_array.std(axis=0)

(3.452052529534663, array([3.26598632, 3.26598632, 3.26598632, 3.26598632]))

## concatenate

In [12]:
a = np.array([1,2,3])
b = np.array([5,7,8])
c = np.vstack((a,b))
c

array([[1, 2, 3],
       [5, 7, 8]])

In [14]:
a = np.array([[1],[2],[3]])
b = np.array([[5],[7],[8]])
c = np.hstack((a,b))
c

array([[1, 5],
       [2, 7],
       [3, 8]])

In [17]:
a = np.array([[1, 2, 3]])
b = np.array([[5, 7, 8]])
c = np.concatenate((a,b), axis=0)
c

array([[1, 2, 3],
       [5, 7, 8]])

In [18]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
c = np.concatenate((a,b.T), axis=1)
c

array([[1, 2, 5],
       [3, 4, 6]])