In [2]:
import numpy as np

In [3]:
def n_size_ndarray_creation(n, dtype=np.int):
    array = np.arange(n**2).reshape(n,n)
    return array

<ipython-input-3-745220d00304>:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  def n_size_ndarray_creation(n, dtype=np.int):


In [5]:
n_size_ndarray_creation(5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [6]:
def zero_or_one_or_empty_ndarray(shape, type_ndarray=0, dtype=np.int):
    if type_ndarray == 0:
        array = np.zeros(shape, dtype)
    elif type_ndarray == 1:
        array = np.ones(shape, dtype)
    elif type_ndarray == 99:
        array = np.empty(shape, dtype)
    
    return array

<ipython-input-6-2c50860bedf4>:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  def zero_or_one_or_empty_ndarray(shape, type_ndarray=0, dtype=np.int):


In [8]:
zero_or_one_or_empty_ndarray( (5,5), type_ndarray=99)

array([[-220424328,        448,         64,          0,          0],
       [         0,          0,          0,          0,          0],
       [1714971698,  892626019,  859202918, 1631138917, 1697801009],
       [ 959985972, 1664377138,  825765943,  912548407,  895706214],
       [ 925905765, 1664102450,  892428855,  959985254, 1664246884]])

In [9]:
def change_shape_of_ndarray(X, n_row):
    if n_row != 1:
        return X.reshape(n_row,-1)
    else:
        return X.reshape(-1)

In [11]:
def concat_ndarray(X_1, X_2, axis):
    try:
        if axis == 0:
            return np.concatenate( (X_1, X_2), axis=0)
        elif axis == 1:
            if len(X_1.shape) == 1 and len(X_2.shape) == 1:
                return np.concatenate( (X_1.reshape(-1, X_1.size), X_2.reshape(-1, X_2.size)), axis=1)
            return np.concatenate( (X_1, X_2), axis=1)
    except:
        return False

In [13]:
a = np.array([1,2])
b = np.array([5,6,7])

In [14]:
concat_ndarray( a, b, axis=1)

array([[1, 2, 5, 6, 7]])

In [31]:
def normalize_ndarray(X, axis=99, dtype=np.float32):
    if axis == 99:
        return (X-np.mean(X))/np.std(X)
    elif axis == 0:
        return (X-np.mean(X, axis=0))/np.std(X, axis=0)
    elif axis == 1:
        return (X-np.mean(X, axis=1).reshape(1, -1))/np.std(X, axis=1).reshape(1, -1)
    
    return array

In [17]:
X = np.arange(12, dtype=np.float32).reshape(6,2)
X

array([[ 0.,  1.],
       [ 2.,  3.],
       [ 4.,  5.],
       [ 6.,  7.],
       [ 8.,  9.],
       [10., 11.]], dtype=float32)

In [27]:
X.mean(axis=1)

array([ 0.5,  2.5,  4.5,  6.5,  8.5, 10.5], dtype=float32)

In [32]:
normalize_ndarray(X, 1)

ValueError: operands could not be broadcast together with shapes (6,2) (1,6) 

In [121]:
def save_ndarray(X, filename="test.npy"):
    np.save(filename, arr=X)

In [137]:
def boolean_index(X, condition):
    return np.where(eval(str("X") + condition))

In [173]:
def find_nearest_value(X, target_value):
    return X[np.argmin(np.abs(X - 0.5))]

In [195]:
def get_n_largest_values(X, n):
    return X[np.argsort(X)[-5:]][::-1]