In [1]:
import numpy as np

In [2]:
weight_vector = np.array([[1],[1],[1]])
x_vector = np.array([[3],[4],[5]])

In [3]:
weight_vector.T

array([[1, 1, 1]])

In [4]:
weight_vector.T.dot(x_vector)

array([[12]])

In [5]:
import pandas as pd

In [6]:
data_url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/housing/housing.data'
df_data = pd.read_csv(data_url, sep='\s+', header = None)
df_data.columns = ['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX', 'PTRATIO', 'B', 'LSTAT','MEDV']
df_data.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296.0   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242.0   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242.0   
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222.0   
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222.0   

   PTRATIO       B  LSTAT  MEDV  
0     15.3  396.90   4.98  24.0  
1     17.8  396.90   9.14  21.6  
2     17.8  392.83   4.03  34.7  
3     18.7  394.63   2.94  33.4  
4     18.7  396.90   5.33  36.2

In [9]:
df_data.values

array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 3.9690e+02, 4.9800e+00,
        2.4000e+01],
       [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 3.9690e+02, 9.1400e+00,
        2.1600e+01],
       [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 3.9283e+02, 4.0300e+00,
        3.4700e+01],
       ...,
       [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 3.9690e+02, 5.6400e+00,
        2.3900e+01],
       [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 3.9345e+02, 6.4800e+00,
        2.2000e+01],
       [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 3.9690e+02, 7.8800e+00,
        1.1900e+01]])

In [11]:
df_data['weights_0'] = 1
df_data.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296.0   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242.0   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242.0   
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222.0   
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222.0   

   PTRATIO       B  LSTAT  MEDV  weights_0  
0     15.3  396.90   4.98  24.0          1  
1     17.8  396.90   9.14  21.6          1  
2     17.8  392.83   4.03  34.7          1  
3     18.7  394.63   2.94  33.4          1  
4     18.7  396.90   5.33  36.2          1

In [12]:
df_data = df_data.drop("MEDV", axis=1)
df_data.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296.0   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242.0   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242.0   
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222.0   
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222.0   

   PTRATIO       B  LSTAT  weights_0  
0     15.3  396.90   4.98          1  
1     17.8  396.90   9.14          1  
2     17.8  392.83   4.03          1  
3     18.7  394.63   2.94          1  
4     18.7  396.90   5.33          1

In [15]:
df_data.shape

(506, 14)

In [17]:
df_matrix = df_data.values
weight_vector = np.random.random_sample((14,1))

In [20]:
weight_vector

array([[0.56737104],
       [0.00372094],
       [0.60755672],
       [0.56120557],
       [0.86167883],
       [0.21093949],
       [0.5883877 ],
       [0.41082404],
       [0.97677159],
       [0.80178746],
       [0.61950458],
       [0.33626576],
       [0.19989756],
       [0.46446194]])

In [21]:
df_matrix.dot(weight_vector)

array([[426.07578613],
       [397.30257718],
       [384.60034445],
       [358.91687846],
       [365.1526547 ],
       [366.66810826],
       [447.70091986],
       [467.06470598],
       [468.03864852],
       [457.46942259],
       [465.04422461],
       [458.18631279],
       [430.33427106],
       [443.96252105],
       [451.9773131 ],
       [440.34420073],
       [421.27650965],
       [453.45124897],
       [393.154235  ],
       [446.72941675],
       [460.93469468],
       [459.57217739],
       [463.72876513],
       [467.89141716],
       [463.64701904],
       [428.18188329],
       [455.2936099 ],
       [431.31453898],
       [461.13113492],
       [454.27638968],
       [453.52249699],
       [460.83046418],
       [404.62313886],
       [452.55789633],
       [417.26339306],
       [423.18785574],
       [413.03596297],
       [407.52332231],
       [400.0221774 ],
       [369.57526529],
       [365.66769074],
       [342.00929771],
       [343.57545328],
       [347

In [22]:
(df_matrix.dot(weight_vector)).shape

(506, 1)