In [1]:
import numpy as np

## Element-wise operations 

In [2]:
test_a = np.array([[1,2,3],[4,5,6]])

In [3]:
test_a + test_a

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [4]:
test_a - test_a

array([[0, 0, 0],
       [0, 0, 0]])

In [5]:
test_a * test_a

array([[ 1,  4,  9],
       [16, 25, 36]])

## dot product

In [7]:
a = np.arange(1,7).reshape(2,3)
b = np.arange(7,13).reshape(3,2)
a.dot(b)

array([[ 58,  64],
       [139, 154]])

## transpose

In [8]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [10]:
a.dot(a.T)

array([[14, 32],
       [32, 77]])

In [11]:
a.T.dot(a)

array([[17, 22, 27],
       [22, 29, 36],
       [27, 36, 45]])

## broadcasting

In [13]:
a + 3

array([[4, 5, 6],
       [7, 8, 9]])

In [14]:
a - 2

array([[-1,  0,  1],
       [ 2,  3,  4]])

In [15]:
a * 4

array([[ 4,  8, 12],
       [16, 20, 24]])

In [16]:
a / 2

array([[0.5, 1. , 1.5],
       [2. , 2.5, 3. ]])

In [17]:
a // 0.2

array([[ 4.,  9., 14.],
       [19., 24., 29.]])

In [18]:
a ** 3

array([[  1,   8,  27],
       [ 64, 125, 216]], dtype=int32)

In [20]:
test_matrix = np.arange(1,13).reshape(4,3)
test_vector = np.arange(10,40,10)
test_matrix + test_vector

array([[11, 22, 33],
       [14, 25, 36],
       [17, 28, 39],
       [20, 31, 42]])