In [1]:
import numpy as np

## boolean index

In [3]:
a = np.array([1,4,0,2,3,8,9,7])
a > 3

array([False,  True, False, False, False,  True,  True,  True])

In [4]:
a[a > 3]

array([4, 8, 9, 7])

In [5]:
condition = a < 3
a[condition]

array([1, 0, 2])

In [13]:
A = np.random.randint(1,21, size=(9,9))
B = A < 10

In [14]:
B

array([[False,  True, False,  True,  True, False,  True, False, False],
       [False, False, False,  True,  True, False,  True, False,  True],
       [ True, False,  True,  True,  True, False, False, False, False],
       [False, False, False,  True, False, False, False,  True, False],
       [ True, False, False,  True, False, False,  True, False, False],
       [False, False, False,  True,  True,  True,  True, False,  True],
       [False, False, False,  True, False, False,  True,  True, False],
       [ True,  True, False,  True,  True,  True, False, False,  True],
       [False, False, False, False, False,  True, False,  True, False]])

In [15]:
B.astype(np.int)

array([[0, 1, 0, 1, 1, 0, 1, 0, 0],
       [0, 0, 0, 1, 1, 0, 1, 0, 1],
       [1, 0, 1, 1, 1, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 1, 0],
       [1, 0, 0, 1, 0, 0, 1, 0, 0],
       [0, 0, 0, 1, 1, 1, 1, 0, 1],
       [0, 0, 0, 1, 0, 0, 1, 1, 0],
       [1, 1, 0, 1, 1, 1, 0, 0, 1],
       [0, 0, 0, 0, 0, 1, 0, 1, 0]])

## fancy index

In [16]:
a = np.array([2, 4, 6, 8])
b = np.array([0, 0 ,1, 3, 2, 1], int)    # 반드시 integer로 선언
a[b]

array([2, 2, 4, 8, 6, 4])

In [17]:
a.take(b)

array([2, 2, 4, 8, 6, 4])

In [19]:
a = np.array([[1,4],[9, 16]])
b = np.array([0,0,1,1,0], int)
c = np.array([0,1,1,0,1], int)
a[b,c]

array([ 1,  4, 16,  9,  4])