In [1]:
import numpy as np

## All & Any

In [2]:
a = np.arange(10)

In [5]:
np.all(a>5), np.all(a<10)

(False, True)

In [6]:
np.any(a>5), np.any(a<0)

(True, False)

In [7]:
a<0

array([False, False, False, False, False, False, False, False, False,
       False])

## Comparision operation #1

In [8]:
test_a = np.array([1, 3, 0], float)
test_b = np.array([5, 2, 1], float)
test_a > test_b

array([False,  True, False])

In [9]:
test_a == test_b

array([False, False, False])

## Comparision operation #2

In [12]:
np.logical_and(test_a > 0, test_a < 3)

array([ True, False, False])

In [13]:
b = np.array([True, False, True], bool)
np.logical_not(b > 0, b < 3)

array([False,  True, False])

In [14]:
c = np.array([False, True, False], bool)
np.logical_or(b,c)

array([ True,  True,  True])

## np.where

In [16]:
np.where(test_a > 0, 3, 2)

array([3, 3, 2])

In [17]:
np.where(a > 5)

(array([6, 7, 8, 9], dtype=int64),)

In [18]:
a = np.array([1,np.NaN, np.Inf], float)
np.isnan(a)

array([False,  True, False])

In [19]:
np.isfinite(a)

array([ True, False, False])

## argmax & argmin

In [20]:
a = np.array([1,2,4,5,8,78,23,3])
np.argmax(a), np.argmin(a)

(5, 0)

In [21]:
a = np.array([[1,2,4,7], [9,88,6,45],[9,76,3,4]])
np.argmax(a, axis=1), np.argmin(a, axis=0)

(array([3, 1, 1], dtype=int64), array([0, 0, 2, 2], dtype=int64))