In [1]:
import numpy as np

## indexing

In [2]:
test_example = np.array([[1,2,3], [4.5,5,6]], int)
test_exampleple

array([[1, 2, 3],
       [4, 5, 6]])

In [3]:
test_example[0][0]

1

In [4]:
test_example[0,0]

1

In [5]:
test_example[0,2] = 10    # Matrix 0,2 에 10 할당
test_example

array([[ 1,  2, 10],
       [ 4,  5,  6]])

## slicing

In [7]:
a = np.array([[1,2,3,4,5],[6,7,8,9,10]],int)

In [8]:
a[:,2:]    # 전체 Row의 2열 이상

array([[ 3,  4,  5],
       [ 8,  9, 10]])

In [9]:
a[1,1:3]    # 1 Row의 1열 ~ 2열

array([7, 8])

In [10]:
a[1:3]    # 1 Row ~ 2 Row의 전체

array([[ 6,  7,  8,  9, 10]])